### PR TITLE
Allow passing seed paramter to TPESampler

### PR DESCRIPTION
**Pull request by henry0312**

### CODE REVIEW

**Comment by sile** [comment]
Thank you for your PR.

To keep the API of `Study` simple, in such case, we would like to pass `TPESamler(seed = seed)` directly as the value of `sampler` argument instead of adding the new argument for a special purpose.

Instead, we are planning to add an [FAQ](https://optuna.readthedocs.io/en/stable/faq.html) entry describing "how to specify random seeds" to make it easy for users to know the way.

We cannot adopt your PR; however, we appreciate your contribution.

**Comment by henry0312** [comment]
Thank you for your review.
How about just setting seed like the below?

```diff
diff --git a/optuna/study.py b/optuna/study.py
--- a/optuna/study.py
+++ b/optuna/study.py
@@ -67,7 +67,7 @@ class Study(object):

         self.study_name = study_name
         self.storage = storages.get_storage(storage)
-        self.sampler = sampler or samplers.TPESampler()
+        self.sampler = sampler or samplers.TPESampler(seed=42)
         self.pruner = pruner or pruners.MedianPruner()

         self.study_id = self.storage.get_study_id_from_name(study_name)
```

**Comment by sile** [comment]
By default, we would like to use random seeds rather than a fixed seed.

**Comment by henry0312** [comment]
Okay, I got it.

**Pull request closed without merging**
