### PR TITLE
[WIP] feat: Simulated Annealing sampler #346

### PR DESCRIPTION
**Pull request by Rishav1**
Based on Simulated Annealing, the SASampler extends TPESampler. For reference,
visit pdfs.semanticscholar.org/1641/02e1de166a75ca09ae8ae154bca2ce32649e.pdf.
The main difference between TPESampler and SASampler is that instead of using
arbitary splits (lower and upper based on trial scores), we construct a sequence
of states (denoted by X) over actual scores (dentoe by Y) accordint to SA algo.
By constructing a Parzen estiamtes on X and Y sequence and sampling from KDE of
X & ~Y distribution (instead of lower & ~upper in case of TPESampler), we get
the sampling distribution.

### CODE REVIEW

**Comment by Rishav1** [comment]
#346

**Comment by Rishav1** [comment]
@sile Can you review the idea? Also, I am getting flake8 errors unrelated to my changes. Any idea why?

**Comment by sile** [comment]
Thank you for your PR. We find it interesting to improve TPE with SA.
However, we'll not merge this PR because it seems experimental.
In the official repository, we would like to provide practically established sampling/pruning methods such as Gaussian Process, CMA-ES or pure Simulated Annealing.

**Comment by sile** [comment]
It is welcome to publish your implementation as a third party sampler in your repository (but be careful as the sampler interface will be changed in the near future as mentioned in https://github.com/pfnet/optuna/issues/346).

**Comment by sile** [comment]
> I am getting flake8 errors unrelated to my changes. Any idea why?

It seems to be due to [this change](https://github.com/pfnet/optuna/pull/358/files#diff-380c6a8ebbbce17d55d50ef17d3cf906R10) (but I'm not sure why flake8 emits additional errors when `ignore = H306` is specified).

**Comment by Rishav1** [comment]
Implementing pure Simulated Annealing actually would require changes in architecture. I think these changes would eventually come up anyways, so here are my suggestions on that.

- Add optional abstract callback function in BaseSampler and BasePruner, which is triggered for each trial on execution of trial.report(), supplying the trial_id and reported score.

- Add functionality for shared user variables across trials. The current storage.get/set_user_attr expects a trial_id. There should be additional functions to access serialized user_attr (perhaps based on trial_id or report timestamp) so that finding moving averages or last-k of user_attr is simple.

**Pull request closed without merging**
