### PR TITLE
Add cascade settings

### PR DESCRIPTION
**Pull request by c-bata**
When removing study record, related records of trial and other tables are still exist. In this PR, I add cascade option (refs #421).

https://docs.sqlalchemy.org/en/13/orm/cascades.html

### CODE REVIEW

**Comment by vasinkd** [comment]
Are you sure that we need a migration file?
We can just implement a database version tracking and tell users that study.delete() is available if only they created database with the latest version of library.

**Comment by vasinkd** [comment]
Not sure whether it's helpful, but here are the command I used to create CASCADE restrictions using Postgres:
```
alter table study_system_attributes drop constraint study_system_attributes_study_id_fkey;
alter table study_system_attributes add constraint study_system_attributes_study_id_fkey foreign key (study_id) REFERENCES studies(study_id) ON DELETE CASCADE;

alter table study_user_attributes drop constraint study_user_attributes_study_id_fkey;
alter table study_user_attributes add constraint study_user_attributes_study_id_fkey  foreign key (study_id) REFERENCES studies(study_id) ON DELETE CASCADE;

alter table trials drop constraint trials_study_id_fkey;
alter table trials add constraint trials_study_id_fkey foreign key (study_id) REFERENCES studies(study_id) ON DELETE CASCADE;

alter table trial_params drop constraint trial_params_trial_id_fkey;
alter table trial_params add constraint trial_params_trial_id_fkey FOREIGN KEY (trial_id) REFERENCES trials(trial_id) ON DELETE CASCADE;

alter table trial_system_attributes drop constraint trial_system_attributes_trial_id_fkey;
alter table trial_system_attributes add constraint trial_system_attributes_trial_id_fkey FOREIGN KEY (trial_id) REFERENCES trials(trial_id) ON DELETE CASCADE;

alter table trial_user_attributes drop constraint trial_user_attributes_trial_id_fkey;
alter table trial_user_attributes add constraint trial_user_attributes_trial_id_fkey FOREIGN KEY (trial_id) REFERENCES trials(trial_id) ON DELETE CASCADE;

alter table trial_values drop constraint trial_values_trial_id_fkey;
alter table trial_values add constraint trial_values_trial_id_fkey FOREIGN KEY (trial_id) REFERENCES trials(trial_id) ON DELETE CASCADE;
```

**Comment by c-bata** [comment]
@vasinkd Sorry for late reply and thank you for your helpful comments!

I wanted to add Foreign Key level ON DELETE cascade settings, but now I feel the difference between each relational databases are little bit complex (especially the prerequisites of SQLite is hard. see https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#foreign-key-support for details).

So I set ORM-level ON DELETE cascade option which provided by SQLAlchemy. ORM-level cascade option requires more DELETE queries than database-level, but it's so simple and doesn't require additional migration files. To check whether this option take expected behaviors, I added `delete_study` method in Storage classes and added tests.

@sile If there is the something concerns (especially about performance), please tell me. I'll try to add ForeignKeyConstraint on alchemy models and add migration files.

**Comment by c-bata** [comment]
Hi! This is ready for review.

**Comment by g-votte** [comment]
Merged the PR.

@c-bata 
Thanks for your contribution!

**Pull request merged**
