### PR TITLE
[WIP] Add trial queue.

### PR DESCRIPTION
**Pull request by sile**
This PR adds `Study.enqueue_trial` method.

```python
import optuna

def objective(trial):
    x = trial.suggest_uniform('x', -100, 100)
    y = trial.suggest_categorical('y', [-1, 0, 1])
    return x**2 + y


if __name__ == '__main__':
    study = optuna.create_study()

    study.enqueue_trial({'x': -99})
    study.enqueue_trial({'x': 99})
    study.enqueue_trial({'x': 0})

    study.optimize(objective, n_trials=10)
    print('Best value: {} (params: {})\n'.format(study.best_value, study.best_params))
```

## TODO

- [ ] Add tests
- [ ] Add migration script (alembic)
- [ ] Change base branch to `master` after #464 is merged

### CODE REVIEW

**Comment by c-bata** [comment]
I tried to modify the implementation of  https://github.com/pfnet/optuna/pull/404, I bumped into the problem.

To enqueue promotable trials, the `SuccessiveHalvingPruner` class needs to get a `Study` class object. The pruner can get a `StudySummary` object but I have no idea to get `Study` class object. I think it's resolved if `inject_trial` method is defined in `storage` interface.

May I have your opinion about this?

**Comment by sile** [comment]
@c-bata 

Thank you for your useful feedback.

> I think it's resolved if `inject_trial` method is defined in `storage` interface.

I think that it's one of the solutions.
However, because `storage` is an internal component of optuna, I want to hide it from users (implementers of samplers and pruners) as much as possible.
I think that it's better to update pruner's interface as follows, and implement `inject_trial` and `enqueue_trial` methods to [`InTrialStudy`](https://optuna.readthedocs.io/en/stable/reference/study.html#optuna.study.InTrialStudy).
```python
class BasePruner(object):
    def prune(self, study, trial, step):
        # type: (InTrialStudy, FronzenTrial, int) -> bool
        raise NotImplementedError
```
```

**Comment by c-bata** [comment]
> I think that it's better to update pruner's interface as follows, and implement inject_trial and enqueue_trial methods to InTrialStudy.

I see. I agree your opinion. So you mean changing pruner interface to pass InTrialStudy like the change of sampler interface, right? I guess the new pruner interface might be like:

```python
@six.add_metaclass(abc.ABCMeta)
class BasePruner(object):
    """Base class for pruners."""

    @abc.abstractmethod
    def prune(self, storage, study, trial, step):
        # type: (BaseStorage, InTrialStudy, FrozenTrial, int) -> bool
```

**Comment by c-bata** [comment]
Sorry, I don't know why but I was misreading your comment.

> I think that it's better to update pruner's interface as follows, and implement inject_trial and enqueue_trial methods to InTrialStudy.

**Comment by c-bata** [comment]
I'm working on this PR at PyCon JP Sprint.

**Comment by sile** [comment]
Closing this PR. Please review #520 instead.

**Pull request closed without merging**
