### PR TITLE
Apply maximize to examples

### PR DESCRIPTION
**Pull request by nmasahiro**
Addresses the issue #406

### CODE REVIEW

**Comment by c-bata** [comment]
We can also apply this change into example code in README.md.
https://github.com/pfnet/optuna/blame/master/README.md#L64

**Comment by nmasahiro** [comment]
> We can also apply this change into example code in README.md.
> https://github.com/pfnet/optuna/blame/master/README.md#L64

Thank you for your comment.
However, I am wondering if I should do that, because the default direction of optuna is minimize, so the example in README.md may confuse the user if it uses maximize.

**Comment by c-bata** [comment]
Certainly. I agree to keep example code of REAMDE as the minimize problem.

**Comment by toshihikoyanase** [comment]
@c-bata @nmasahiro
We’re planning to revise `README.md` to reflect the recent updates in the near future, and we’ll take this discussion into account. Thank you!

**Comment by sile** [comment]
I think that we can modify `examples/chainermn_simple.py` and `examples/pruning/*.py`  as well.

**Comment by sile** [comment]
We created an issue https://github.com/pfnet/optuna/issues/453 for pruning examples and will merge this PR.
Thank you for your contribution!

**Pull request merged**
